# permissions for end users to edit namespacetemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespacetemplate-editor-role
rules:
- apiGroups:
  - mega.aragunathan.com
  resources:
  - namespacetemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mega.aragunathan.com
  resources:
  - namespacetemplates/status
  verbs:
  - get
