
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - mega.aragunathan.com
  resources:
  - namespacetemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mega.aragunathan.com
  resources:
  - namespacetemplates/status
  verbs:
  - get
  - patch
  - update
