apiVersion: mega.aragunathan.com/v1
kind: NamespaceTemplate
metadata:
  name: namespacetemplate-sample
spec:
  postcreatehook:
    command: ["kubectl", "create", "serviceaccount", "nginx-serviceaccount"]
  options:
    my-awesome-key1: my-awesome-value1
    my-awesome-key2: my-awesome-value2
    my-awesome-key3: my-awesome-value3
    my-awesome-key4: my-awesome-value4
  addresources:
    pod:
      metadata:
        name: test-pod
      spec:
        containers:
        - name: web
          image: nginx
          imagePullPolicy: Always
          ports:
          - containerPort: 80
    secret:
      metadata:
        name: test-secret
      type: Opaque
      data:
        username: YWRtaW4=
        password: MWYyZDFlMmU2N2Rm
    limitrange:
      metadata:
        name: test-limitrange
      spec:
        limits:
        - max:
            cpu: "800m"
            memory: "1Gi"
          min:
            cpu: "100m"
            memory: "99Mi"
          default:
            cpu: "700m"
            memory: "900Mi"
          defaultRequest:
            cpu: "110m"
            memory: "111Mi"
          type: Container
